#version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: votre_utilisateur
      POSTGRES_PASSWORD: votre_mot_de_passe
      POSTGRES_DB: votre_base_de_donnees
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Remplacez par votre e-mail
      PGADMIN_DEFAULT_PASSWORD: admin # Mot de passe pour pgAdmin
    ports:
      - "5050:80"  # Le port 5050 de votre machine sera mappé au port 80 du conteneur pgAdmin
    networks:
      - django_network
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  django_network:
