# Generated by Django 5.1.2 on 2024-11-09 23:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alevin',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.infrastructure'),
        ),
        migrations.AddField(
            model_name='pechecontrole',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.infrastructure'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.infrastructure'),
        ),
        migrations.AddField(
            model_name='recolte',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.infrastructure'),
        ),
        migrations.AlterField(
            model_name='recolte',
            name='dateVenteAutres',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Autre - Date de vente'),
        ),
        migrations.AlterField(
            model_name='recolte',
            name='dateVenteClarias',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Clarias - Date de vente'),
        ),
        migrations.AlterField(
            model_name='recolte',
            name='dateVenteTilapia',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Tilapia - Date vente'),
        ),
    ]
