# Generated by Django 5.1.2 on 2025-05-31 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlleur',
            name='categorie',
            field=models.CharField(choices=[('CS', 'CHEF SECTEUR'), ('DR', 'DIRECTEUR REGIONALE'), ('S', 'SUPERVISEUR')], max_length=2),
        ),
        migrations.CreateModel(
            name='AgentEncadrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_encadrement_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pisciculteur',
            name='agent_encadrement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.agentencadrement'),
        ),
    ]
