# Generated by Django 5.1.2 on 2025-06-04 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0002_alter_controlleur_categorie_agentencadrement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferme',
            name='zone',
        ),
        migrations.AddField(
            model_name='ferme',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.quartier'),
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
