# Generated by Django 5.1.2 on 2024-11-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0002_alevin_infrastructure_pechecontrole_infrastructure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeinfrastructure',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
