# Generated by Django 5.1.2 on 2025-06-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0003_remove_ferme_zone_ferme_quartier_delete_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeinfrastructure',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='typeInfrastructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionferme.typeinfrastructure', verbose_name="Type d'Infrastructure"),
        ),
    ]
