# Generated by Django 5.1.2 on 2024-11-10 00:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0003_alter_typeinfrastructure_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alevin',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.typeinfrastructure'),
        ),
        migrations.AlterField(
            model_name='pechecontrole',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.typeinfrastructure'),
        ),
        migrations.AlterField(
            model_name='rationjournaliere',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.typeinfrastructure'),
        ),
        migrations.AlterField(
            model_name='recolte',
            name='dateVenteAutres',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Autres - Date de vente'),
        ),
        migrations.AlterField(
            model_name='recolte',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.typeinfrastructure'),
        ),
    ]
