# Generated by Django 5.1.2 on 2024-11-10 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0004_alter_alevin_infrastructure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alevin',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.infrastructure'),
        ),
        migrations.AlterField(
            model_name='pechecontrole',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.infrastructure'),
        ),
        migrations.AlterField(
            model_name='rationjournaliere',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.infrastructure'),
        ),
        migrations.AlterField(
            model_name='recolte',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.infrastructure'),
        ),
    ]
