# Generated by Django 5.1.2 on 2025-06-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0004_typeinfrastructure_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeinfrastructure',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
