# Generated by Django 5.1.2 on 2025-06-07 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0005_alter_typeinfrastructure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='ChefSecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cercle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.cercle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_secteur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirecteurRegionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directeur_regionnale_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
