# Generated by Django 5.1.2 on 2025-06-07 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0006_alter_infrastructure_numero_chefsecteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefsecteur',
            name='cercle',
        ),
        migrations.RemoveField(
            model_name='directeurregionale',
            name='region',
        ),
        migrations.CreateModel(
            name='ChefSecteurCercle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cercle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionferme.cercle')),
                ('chef_secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionferme.chefsecteur')),
            ],
            options={
                'unique_together': {('chef_secteur', 'cercle')},
            },
        ),
        migrations.AddField(
            model_name='chefsecteur',
            name='cercles',
            field=models.ManyToManyField(blank=True, through='gestionferme.ChefSecteurCercle', to='gestionferme.cercle'),
        ),
        migrations.AddField(
            model_name='directeurregionale',
            name='region',
            field=models.ManyToManyField(blank=True, to='gestionferme.region'),
        ),
    ]
