# Generated by Django 5.1.2 on 2025-01-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0006_dashboard_alter_typeinfrastructure_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alevin',
            name='coutAchatTilapia',
            field=models.PositiveIntegerField(default=0, verbose_name='Coût Achat Tilapia'),
        ),
    ]
