# Generated by Django 5.1.2 on 2025-06-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0007_remove_chefsecteur_cercle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirecteurRegionale',
        ),
    ]
