# Generated by Django 5.1.2 on 2025-06-11 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0008_delete_directeurregionale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationRegionDirecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionferme.region')),
            ],
        ),
        migrations.CreateModel(
            name='DirecteurRegionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('region', models.ManyToManyField(blank=True, through='gestionferme.AffectationRegionDirecteur', to='gestionferme.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directeur_regionnale_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='affectationregiondirecteur',
            name='directeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionferme.directeurregionale'),
        ),
        migrations.AlterUniqueTogether(
            name='affectationregiondirecteur',
            unique_together={('directeur', 'region')},
        ),
    ]
