# Generated by Django 5.1.2 on 2025-01-28 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0008_aliment_remove_rationjournaliere_aliment1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Produit')),
                ('quantite', models.FloatField(default=0)),
                ('prix', models.PositiveIntegerField(default=0, verbose_name='Prix Produit')),
            ],
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliment1_rationJournaliere', to='gestionferme.aliment'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliment2_rationJournaliere', to='gestionferme.aliment'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliment3_rationJournaliere', to='gestionferme.aliment'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliment4_rationJournaliere', to='gestionferme.aliment'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliment5_rationJournaliere', to='gestionferme.aliment'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Aliment'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='prix',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix Aliment'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='produit1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit1_rationJournaliere', to='gestionferme.produit'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='produit2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit2_rationJournaliere', to='gestionferme.produit'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='produit3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit3_rationJournaliere', to='gestionferme.produit'),
        ),
    ]
