# Generated by Django 5.1.2 on 2025-06-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0009_affectationregiondirecteur_directeurregionale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationjournaliere',
            name='taux_ration',
            field=models.FloatField(default=0, verbose_name='Taux Ration'),
        ),
    ]
