# Generated by Django 5.1.2 on 2025-01-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0010_rationjournaliere_nom_rationjournaliere_prixaliment1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eau', models.PositiveIntegerField(default=0, verbose_name='Total Eau')),
                ('main_oeuvre', models.PositiveIntegerField(default=0, verbose_name="Total Main d'oeuvre")),
                ('amortissements', models.PositiveIntegerField(default=0, verbose_name='Total Amortissement')),
                ('cycleProduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionferme.cycleproduction')),
            ],
        ),
    ]
