# Generated by Django 5.1.2 on 2025-07-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0011_pechecontrole_prise_poids_autres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pechecontrole',
            name='biomasse',
        ),
        migrations.RemoveField(
            model_name='pechecontrole',
            name='poidsMoyen',
        ),
        migrations.RemoveField(
            model_name='pechecontrole',
            name='poidsTotalEchantillons',
        ),
        migrations.RemoveField(
            model_name='pechecontrole',
            name='prisePoidsTotal',
        ),
        migrations.RemoveField(
            model_name='pechecontrole',
            name='prise_poids_autres',
        ),
        migrations.RemoveField(
            model_name='pechecontrole',
            name='prise_poids_claria',
        ),
        migrations.RemoveField(
            model_name='pechecontrole',
            name='prise_poids_tilapia',
        ),
    ]
