# Generated by Django 5.1.2 on 2025-01-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0012_cycleproduction_cycle_cycleproduction_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycleproduction',
            name='cycle',
            field=models.BooleanField(default=False, verbose_name='Valider la fin de cycle'),
        ),
    ]
