# Generated by Django 5.1.2 on 2025-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0012_remove_pechecontrole_biomasse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pechecontrole',
            name='prise_poids_autres',
            field=models.FloatField(default=0, verbose_name='Prise Poids Autres'),
        ),
        migrations.AddField(
            model_name='pechecontrole',
            name='prise_poids_claria',
            field=models.FloatField(default=0, verbose_name='Prise Poids Claria'),
        ),
        migrations.AddField(
            model_name='pechecontrole',
            name='prise_poids_tilapia',
            field=models.FloatField(default=0, verbose_name='Prise Poids Tilapia'),
        ),
    ]
