# Generated by Django 5.1.2 on 2025-07-30 18:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0013_pechecontrole_prise_poids_autres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyclesRation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycleProduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionferme.cycleproduction')),
                ('infrastructure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionferme.infrastructure')),
            ],
        ),
        migrations.CreateModel(
            name='Ration1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('aliment1', models.FloatField(default=0, verbose_name='Aliment 1')),
                ('prixAliment1', models.PositiveIntegerField(default=0, verbose_name='Prix Aliment 1')),
                ('aliment2', models.FloatField(default=0, verbose_name='Aliment 2')),
                ('cyclesRation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionferme.cyclesration')),
            ],
        ),
        migrations.CreateModel(
            name='Ration2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('aliment1', models.FloatField(default=0, verbose_name='Aliment 1')),
                ('prixAliment1', models.PositiveIntegerField(default=0, verbose_name='Prix Aliment 1')),
                ('aliment2', models.FloatField(default=0, verbose_name='Aliment 2')),
                ('cyclesRation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionferme.cyclesration')),
            ],
        ),
    ]
