# Generated by Django 5.1.2 on 2025-01-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0013_alter_cycleproduction_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycleproduction',
            name='cycle',
        ),
    ]
