# Generated by Django 5.1.2 on 2025-01-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0014_remove_cycleproduction_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleproduction',
            name='cycle',
            field=models.CharField(choices=[('ENCOURS', 'ENCOURS'), ('TERMINE', 'TERMINE')], default='ENCOURS', max_length=20),
        ),
    ]
