# Generated by Django 5.1.2 on 2025-07-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0014_cyclesration_ration1_ration2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyclesration',
            name='cycleProduction',
        ),
        migrations.RemoveField(
            model_name='cyclesration',
            name='infrastructure',
        ),
        migrations.RemoveField(
            model_name='ration2',
            name='cyclesRation',
        ),
        migrations.DeleteModel(
            name='Ration1',
        ),
        migrations.DeleteModel(
            name='CyclesRation',
        ),
        migrations.DeleteModel(
            name='Ration2',
        ),
    ]
