# Generated by Django 5.1.2 on 2025-08-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0015_remove_cyclesration_cycleproduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='nom',
        ),
        migrations.AlterField(
            model_name='pechecontrole',
            name='nombreTotalPoissonsEchantillonnes',
            field=models.PositiveIntegerField(default=0, verbose_name='Nbre Total poissons échant.'),
        ),
    ]
