# Generated by Django 5.1.2 on 2025-02-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0015_cycleproduction_cycle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charges',
            new_name='Charge',
        ),
        migrations.AlterField(
            model_name='cycleproduction',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de cycle'),
        ),
    ]
