# Generated by Django 5.1.2 on 2025-08-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0016_remove_rationjournaliere_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationjournaliere',
            name='produit_utilise',
            field=models.BooleanField(default=False, verbose_name='Utilisé ?'),
        ),
    ]
