# Generated by Django 5.1.2 on 2025-08-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0017_rationjournaliere_produit_utilise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='aliment1',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='aliment2',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='aliment3',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='aliment4',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='aliment5',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='prixAliment1',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='prixAliment2',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='prixAliment3',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='prixAliment4',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='prixAliment5',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='prixProduit1',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='prixProduit2',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='prixProduit3',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='produit1',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='produit2',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='produit3',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='produit_utilise',
        ),
    ]
