# Generated by Django 5.1.2 on 2025-08-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0018_remove_rationjournaliere_aliment1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment1',
            field=models.BooleanField(default=False, verbose_name='Aliment1 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment1_cycle2',
            field=models.BooleanField(default=False, verbose_name='Aliment1 C2 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment2',
            field=models.BooleanField(default=False, verbose_name='Aliment2 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment2_cycle2',
            field=models.BooleanField(default=False, verbose_name='Aliment2 C2 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment3',
            field=models.BooleanField(default=False, verbose_name='Aliment3 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment3_cycle2',
            field=models.BooleanField(default=False, verbose_name='Aliment3 C2 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment4',
            field=models.BooleanField(default=False, verbose_name='Aliment4 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment4_cycle2',
            field=models.BooleanField(default=False, verbose_name='Aliment4 C2 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment5',
            field=models.BooleanField(default=False, verbose_name='Aliment5 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment5_cycle2',
            field=models.BooleanField(default=False, verbose_name='Aliment5 C2 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit1',
            field=models.BooleanField(default=False, verbose_name='Produit1 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit1_cycle2',
            field=models.BooleanField(default=False, verbose_name='Produit1 C2 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit2',
            field=models.BooleanField(default=False, verbose_name='Produit2 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit2_cycle2',
            field=models.BooleanField(default=False, verbose_name='Produit2 C2 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit3',
            field=models.BooleanField(default=False, verbose_name='Produit3 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit3_cycle2',
            field=models.BooleanField(default=False, verbose_name='Produit3 C2 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='prixAliment1',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix Aliment1'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='prixAliment2',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix Aliment2'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='prixAliment3',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix Aliment3'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='prixAliment4',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix Aliment4'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='prixAliment5',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix Aliment5'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='prixProduit1',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix Produit1'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='prixProduit2',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix Produit2'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='prixProduit3',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix Produit3'),
        ),
    ]
