# Generated by Django 5.1.2 on 2025-09-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0019_rationjournaliere_is_aliment1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment1_cycle3',
            field=models.BooleanField(default=False, verbose_name='Aliment1 C3 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment1_cycle4',
            field=models.BooleanField(default=False, verbose_name='Aliment1 C4 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment1_cycle5',
            field=models.BooleanField(default=False, verbose_name='Aliment1 C5 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment1_cycle6',
            field=models.BooleanField(default=False, verbose_name='Aliment1 C6 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment2_cycle3',
            field=models.BooleanField(default=False, verbose_name='Aliment2 C3 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment2_cycle4',
            field=models.BooleanField(default=False, verbose_name='Aliment2 C4 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment2_cycle5',
            field=models.BooleanField(default=False, verbose_name='Aliment2 C5 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment2_cycle6',
            field=models.BooleanField(default=False, verbose_name='Aliment2 C6 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment3_cycle3',
            field=models.BooleanField(default=False, verbose_name='Aliment3 C3 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment3_cycle4',
            field=models.BooleanField(default=False, verbose_name='Aliment3 C4 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment3_cycle5',
            field=models.BooleanField(default=False, verbose_name='Aliment3 C5 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment3_cycle6',
            field=models.BooleanField(default=False, verbose_name='Aliment3 C6 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment4_cycle3',
            field=models.BooleanField(default=False, verbose_name='Aliment4 C3 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment4_cycle4',
            field=models.BooleanField(default=False, verbose_name='Aliment4 C4 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment4_cycle5',
            field=models.BooleanField(default=False, verbose_name='Aliment4 C5 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment4_cycle6',
            field=models.BooleanField(default=False, verbose_name='Aliment4 C6 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment5_cycle3',
            field=models.BooleanField(default=False, verbose_name='Aliment5 C3 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment5_cycle4',
            field=models.BooleanField(default=False, verbose_name='Aliment5 C4 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment5_cycle5',
            field=models.BooleanField(default=False, verbose_name='Aliment5 C5 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment5_cycle6',
            field=models.BooleanField(default=False, verbose_name='Aliment5 C6 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit1_cycle3',
            field=models.BooleanField(default=False, verbose_name='Produit1 C3 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit1_cycle4',
            field=models.BooleanField(default=False, verbose_name='Produit1 C4 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit1_cycle5',
            field=models.BooleanField(default=False, verbose_name='Produit1 C5 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit1_cycle6',
            field=models.BooleanField(default=False, verbose_name='Produit1 C6 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit2_cycle3',
            field=models.BooleanField(default=False, verbose_name='Produit2 C3 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit2_cycle4',
            field=models.BooleanField(default=False, verbose_name='Produit2 C4 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit2_cycle5',
            field=models.BooleanField(default=False, verbose_name='Produit2 C5 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit2_cycle6',
            field=models.BooleanField(default=False, verbose_name='Produit2 C6 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit3_cycle3',
            field=models.BooleanField(default=False, verbose_name='Produit3 C3 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit3_cycle4',
            field=models.BooleanField(default=False, verbose_name='Produit3 C4 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit3_cycle5',
            field=models.BooleanField(default=False, verbose_name='Produit3 C5 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit3_cycle6',
            field=models.BooleanField(default=False, verbose_name='Produit3 C6 ?'),
        ),
    ]
