# Generated by Django 5.1.2 on 2025-09-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0020_rationjournaliere_is_aliment1_cycle3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rationjournaliere',
            old_name='taux_ration',
            new_name='taux_ration_cycle1',
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='taux_ration_cycle2',
            field=models.FloatField(default=0, verbose_name='Taux Ration'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='taux_ration_cycle3',
            field=models.FloatField(default=0, verbose_name='Taux Ration'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='taux_ration_cycle4',
            field=models.FloatField(default=0, verbose_name='Taux Ration'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='taux_ration_cycle5',
            field=models.FloatField(default=0, verbose_name='Taux Ration'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='taux_ration_cycle6',
            field=models.FloatField(default=0, verbose_name='Taux Ration'),
        ),
    ]
