# Generated by Django 5.1.2 on 2025-09-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0021_rename_taux_ration_rationjournaliere_taux_ration_cycle1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='is_aliment1',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='is_aliment2',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='is_aliment3',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='is_aliment4',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='is_aliment5',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='is_produit1',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='is_produit2',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='is_produit3',
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment1_cycle1',
            field=models.BooleanField(default=False, verbose_name='Aliment1 C1 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment2_cycle1',
            field=models.BooleanField(default=False, verbose_name='Aliment2 C1 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment3_cycle1',
            field=models.BooleanField(default=False, verbose_name='Aliment3 C1 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment4_cycle1',
            field=models.BooleanField(default=False, verbose_name='Aliment4 C1 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_aliment5_cycle1',
            field=models.BooleanField(default=False, verbose_name='Aliment5 C1 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit1_cycle1',
            field=models.BooleanField(default=False, verbose_name='Produit1 C1 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit2_cycle1',
            field=models.BooleanField(default=False, verbose_name='Produit2 C1 ?'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='is_produit3_cycle1',
            field=models.BooleanField(default=False, verbose_name='Produit3 C1 ?'),
        ),
        migrations.AlterField(
            model_name='rationjournaliere',
            name='taux_ration_cycle1',
            field=models.FloatField(default=0, verbose_name='Taux Ration C1'),
        ),
        migrations.AlterField(
            model_name='rationjournaliere',
            name='taux_ration_cycle2',
            field=models.FloatField(default=0, verbose_name='Taux Ration C2'),
        ),
        migrations.AlterField(
            model_name='rationjournaliere',
            name='taux_ration_cycle3',
            field=models.FloatField(default=0, verbose_name='Taux Ration C3'),
        ),
        migrations.AlterField(
            model_name='rationjournaliere',
            name='taux_ration_cycle4',
            field=models.FloatField(default=0, verbose_name='Taux Ration C4'),
        ),
        migrations.AlterField(
            model_name='rationjournaliere',
            name='taux_ration_cycle5',
            field=models.FloatField(default=0, verbose_name='Taux Ration C5'),
        ),
        migrations.AlterField(
            model_name='rationjournaliere',
            name='taux_ration_cycle6',
            field=models.FloatField(default=0, verbose_name='Taux Ration C6'),
        ),
    ]
