# Generated by Django 5.1.2 on 2025-09-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0022_remove_rationjournaliere_is_aliment1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment2',
            field=models.FloatField(default=0, verbose_name='Aliment 2'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment3',
            field=models.FloatField(default=0, verbose_name='Aliment 3'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment4',
            field=models.FloatField(default=0, verbose_name='Aliment 4'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment5',
            field=models.FloatField(default=0, verbose_name='Aliment 5'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='nom',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom Ration Journalière'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='produit1',
            field=models.FloatField(blank=True, default=0, verbose_name='Produit 1'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='produit2',
            field=models.FloatField(blank=True, default=0, verbose_name='Produit 2'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='produit3',
            field=models.FloatField(blank=True, default=0, verbose_name='Produit 3'),
        ),
    ]
