# Generated by Django 5.1.2 on 2025-09-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0023_rationjournaliere_aliment2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='aliment2',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='aliment3',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='aliment4',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='aliment5',
        ),
    ]
