# Generated by Django 5.1.2 on 2025-09-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0024_remove_rationjournaliere_aliment2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment1',
            field=models.FloatField(default=0, verbose_name='Aliment 1'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment2',
            field=models.FloatField(default=0, verbose_name='Aliment 2'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment3',
            field=models.FloatField(default=0, verbose_name='Aliment 3'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment4',
            field=models.FloatField(default=0, verbose_name='Aliment 4'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='aliment5',
            field=models.FloatField(default=0, verbose_name='Aliment 5'),
        ),
    ]
