# Generated by Django 5.1.2 on 2025-09-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0025_rationjournaliere_aliment1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='produit1',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='produit2',
        ),
        migrations.RemoveField(
            model_name='rationjournaliere',
            name='produit3',
        ),
    ]
