# Generated by Django 5.1.2 on 2025-09-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionferme', '0026_remove_rationjournaliere_produit1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationjournaliere',
            name='produit1',
            field=models.FloatField(blank=True, default=0, verbose_name='Produit 1'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='produit2',
            field=models.FloatField(blank=True, default=0, verbose_name='Produit 2'),
        ),
        migrations.AddField(
            model_name='rationjournaliere',
            name='produit3',
            field=models.FloatField(blank=True, default=0, verbose_name='Produit 3'),
        ),
    ]
